#ifndef IRIS_ZZ_X4_CORE_TRAITS_WRITE_RANK_HPP
#define IRIS_ZZ_X4_CORE_TRAITS_WRITE_RANK_HPP

/*=============================================================================
    Copyright (c) 2026 The Iris Project Contributors

    Distributed under the Boost Software License, Version 1.0. (See accompanying
    file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
=============================================================================*/

// Important notice: part of this code was generated by an LLM and went through
// more than 120 hours of intensive review by the current maintainer. The LLM was
// used solely to generate the mathematical algorithm (the graph solver) that
// deduces how an attribute is handled.
//
// The semantics behind the algorithm were provided entirely by the maintainer,
// through a dedicated analysis of the existing codebase. While developing the
// theory, the maintainer thoroughly reviewed *every* test case in every `.cpp`
// file, which together carry more than 20 years of history going back to the
// original library.

#include <iris/config.hpp> // IWYU pragma: keep

#include <iris/x4/core/attribute.hpp>
#include <iris/x4/traits/container_traits.hpp>
#include <iris/x4/core/traits/attribute_category.hpp>
#include <iris/x4/core/traits/tuple_traits.hpp>
#include <iris/x4/core/traits/variant_class.hpp>

#include <iris/rvariant/rvariant.hpp>
#include <iris/rvariant/variant_helper.hpp>
#include <iris/alloy/traits.hpp>
#include <iris/string.hpp>
#include <iris/type_traits.hpp>
#include <iris/type_list.hpp>

#include <array>
#include <concepts>
#include <ranges>
#include <type_traits>
#include <utility>

#include <cstddef> // IWYU pragma: keep

namespace iris::x4 {

// How `x4::write_attribute` writes a value into an attribute; the better compares greater
enum class write_rank : unsigned char
{
    // Not writable.
    none,

    // Written, somewhere inside, by an assignment or a construction of the language
    // which converts the value without narrowing.
    assignable_without_narrowing,

    // Written by its shape: appended into a container, member by member, into
    // the content of an optional or an alternative of a variant.
    structural,

    // Assigned from the same plain type.
    exact,
};

namespace detail {

template<class SRef, class V>
struct write_rank_impl;

} // detail

// How a value of type `V` is written into the attribute of type `SRef`.
// `SRef` must be `S&` for a non-const `S`, as the left operand of `iris::weakly_assignable_from` is.
// `V` is the right operand.
template<class SRef, class V>
inline constexpr write_rank write_rank_v = detail::write_rank_impl<SRef, V>::value;

template<class SRef, class V>
inline constexpr bool is_writable_v = write_rank_v<SRef, V> != write_rank::none;

namespace planner {

inline constexpr std::size_t no_index = static_cast<std::size_t>(-1);

// A node is W(S, V), E(S, x) or P(S, y); its branches are in the order of priority. A branch holds
// its condition and the edges to its children.

// W(S, V): the write of `V` into `S`
template<class S, class V>
struct write_node
{
    using storage_type = S;
    using value_type = V;
};

// E(S, x): an element `x` of a range appended into the container `S`
template<class S, class V>
struct range_element_node
{
    using storage_type = S;
    using value_type = V;
};

// P(S, y): a part `y` of a sequence, or the value of one parse of a repetition, appended into the container `S`
template<class S, class V>
struct sequence_part_node
{
    using storage_type = S;
    using value_type = V;
};

// A storage is an object type; a value is the type of an expression (`T` for an rvalue, `T&` or
// `T const&` for an lvalue). `recursive_wrapper` is unwrapped.
template<class T>
using storage_t = unwrap_recursive_t<std::remove_cvref_t<T>>;

template<class V>
using model_value_t = std::conditional_t<
    std::is_lvalue_reference_v<V>,
    unwrap_recursive_t<std::remove_reference_t<V>>&,
    unwrap_recursive_t<std::remove_reference_t<V>>
>;

enum class branch_kind : unsigned char
{
    assign_same,         // `s = v` of the same plain type
    assign,              // `s = v` with a conversion
    transparent,         // `-a`: nothing if absent, else the content
    slots,               // member by member
    single_slot,         // into the element of a single-element tuple-like
    engage_optional,     // an optional from an optional
    engage,              // into the content of an optional
    whole,               // the whole range as one element
    append_all,          // the elements of the same type at once
    each,                // element by element
    same_alternative,
    conversion,          // into the plain alternative selected as P0608
    structural,          // into the alternative written by its shape
    wrapping,            // into the element of the single-element tuple-like alternative
    wrapping_many,       // two or more single-element tuple-like alternatives: ambiguous
    split,               // alternative by alternative of the value
    new_element,
    parts,
    range,
};

// -----------------------------------------------------------------

namespace detail {

// A part of a value, passed on as `std::forward_like<V>` does
template<class V, class Part>
using part_value_t = model_value_t<decltype(iris::unwrap_recursive(std::forward_like<V>(std::declval<Part>())))>;

template<std::size_t I, class V>
using slot_value_t = part_value_t<V, decltype(alloy::get<I>(std::declval<V&>()))>;

template<class V>
using content_value_t = part_value_t<V, decltype(*std::declval<V&>())>;

// An element of a range value as X4 takes it out: moved from an rvalue
template<class V>
using range_element_value_t = model_value_t<std::conditional_t<
    std::is_lvalue_reference_v<V>,
    std::ranges::range_reference_t<V>,
    std::ranges::range_rvalue_reference_t<V>
>>;

// A range whose element is of its own type (`std::filesystem::path`) is not a range
// here, as `[format.range.fmtkind]` does not format it as one
template<class V>
concept range_value =
    (std::same_as<attribute_category_t<std::remove_cvref_t<V>>, container_tag> || std::same_as<attribute_category_t<std::remove_cvref_t<V>>, plain_tag>) &&
    std::ranges::forward_range<std::remove_reference_t<V>> &&
    !std::same_as<std::remove_cvref_t<range_element_value_t<V>>, std::remove_cvref_t<V>>;

// Characters of one type are never written as characters of another
template<class T, class U>
concept both_char_like = CharLike<T> && CharLike<U>;

// `s = v` for a plain `S`. Only a narrowing of the implicit conversion into `S` itself is rejected; one into the
// parameter of a user-defined conversion or assignment operator (`Port <- long long`) is the responsibility of the type
template<class S, class V>
concept plain_writable =
    is_assignable_without_narrowing_v<S&, V> &&
    !x4::detail::dangles<S, V> &&
    !both_char_like<S, std::remove_reference_t<V>>;

// `T` is constructible from the value itself, by direct-initialization where the value converts implicitly
// without narrowing; a type other than plain only from the same type
template<class T, class V>
concept constructible_from_value =
    (std::same_as<std::remove_cvref_t<V>, T> && std::is_convertible_v<V, T>) ||
    (
        !std::same_as<std::remove_cvref_t<V>, T> &&
        std::same_as<attribute_category_t<T>, plain_tag> &&
        is_convertible_without_narrowing_v<V, T> &&
        std::is_constructible_v<T, V> &&
        !x4::detail::dangles<T, V> &&
        !both_char_like<T, std::remove_reference_t<V>>
    );

// Mandated where a write reaches a variant, or makes a new one. Otherwise, whether a new variant can
// be made would depend on the order of its alternatives, and would silently change the candidates.
template<class S, class Category = attribute_category_t<S>>
inline constexpr bool mandates_variant_default_state = true;

template<class S>
inline constexpr bool mandates_variant_default_state<S, variant_tag> = [] {
    static_assert(
        std::is_default_constructible_v<S>,
        "The variant attribute has no default state, as its first alternative is not default constructible. "
        "Reorder the alternatives so that a default constructible one comes first."
    );
    return true;
}();

// A new `T` can be made from the value:
// - A variant is constructed holding the alternative its write selects. It must have the default state
//   (mandated), though the state is not used.
// - A plain `T` is constructed from the value (`T t(v);`, never `T t; t = v;`).
// - A `T` of the type of the value is constructed from the value.
// - Any other `T` must be default constructible.
template<class T, class V>
concept makeable =
    (std::same_as<attribute_category_t<T>, variant_tag> && mandates_variant_default_state<T>) ||
    (!std::same_as<attribute_category_t<T>, plain_tag> && std::is_default_constructible_v<T>) ||
    constructible_from_value<T, V>;

// The elements of the range value `range` to be appended, moved from unless the value is an lvalue
template<class V>
[[nodiscard]] constexpr auto appended_elements(std::remove_reference_t<V>& range) noexcept
{
    if constexpr (std::is_lvalue_reference_v<V&&>) {
        return std::views::all(range);

    } else {
        return range | std::views::as_rvalue;
    }
}

// A descent edge moves the value to a part of it; any other edge is a zero edge
template<class Node, bool Descent>
struct edge
{
    using node = Node;
    static constexpr bool descent = Descent;
};

template<branch_kind Kind, std::size_t Alternative, bool Cond, class... Edges>
struct branch {};

// The candidates at one position, of which the one applying is selected; ambiguous if two apply
template<class... Branches>
struct branch_group {};

template<class T>
inline constexpr bool is_const_part = std::is_const_v<unwrap_recursive_t<std::remove_reference_t<T>>>;

template<class S, class Category = attribute_category_t<S>>
inline constexpr bool has_const_part = false;

template<class S>
inline constexpr bool has_const_part<S, tuple_tag> = []<std::size_t... Is>(std::index_sequence<Is...>) {
    return (is_const_part<alloy::tuple_element_t<Is, S>> || ...);
}(std::make_index_sequence<alloy::tuple_size_v<S>>{});

template<class S>
inline constexpr bool has_const_part<S, optional_tag> = is_const_part<typename S::value_type>;

template<class... Ss>
inline constexpr bool has_const_part<rvariant<Ss...>, variant_tag> = (is_const_part<Ss> || ...);

// Mandated where a write reaches `S`
template<class S>
inline constexpr bool mandates_no_const_part = [] {
    static_assert(
        !has_const_part<S>,
        "The attribute has a const part (a member, an element of a tuple, the content of an optional "
        "or an alternative of a variant), into which no value is ever written"
    );
    return true;
}();

template<class... Branches>
inline constexpr std::type_identity<type_list<Branches...>> branch_list{};

// `-a`: nothing if absent, else the content
template<class S, class V>
using transparent_branch = branch<branch_kind::transparent, no_index, true, edge<write_node<S, content_value_t<V>>, true>>;

// The conditions are concepts so that the heavier checks are skipped once the element types decide them

// The range becomes one new element as a whole (`std::vector<std::string> <- std::vector<char>`)
template<class S, class V>
concept writes_whole_as_element =
    !std::same_as<storage_t<iris::container::element_t<S>>, std::remove_cvref_t<range_element_value_t<V>>> &&
    makeable<storage_t<iris::container::element_t<S>>, V> &&
    iris::container::appendable<S, iris::container::element_t<S>>;

// The elements of the same type are appended at once
template<class S, class V>
concept appends_all =
    std::same_as<storage_t<iris::container::element_t<S>>, std::remove_cvref_t<range_element_value_t<V>>> &&
    requires(S& s, std::remove_reference_t<V>& range) {
        iris::container::append_range(s, detail::appended_elements<V>(range));
    };

// W(S, V) for a variant `S`: the same type, a conversion as P0608 (`std::variant<char, long long> v; v = 42;`
// holds `long long`), the shape, then wrapped; X4 wraps only where it chooses the alternative, as C++:
// `Paren p = {1};` is well-formed, and `std::variant<char, Paren> v = 1;` is not

template<branch_kind Kind, class T, class V>
concept variant_candidate =
    (Kind == branch_kind::same_alternative && std::same_as<T, std::remove_cvref_t<V>>) ||
    (
        Kind == branch_kind::conversion &&
        std::same_as<attribute_category_t<T>, plain_tag> &&
        !std::same_as<T, std::remove_cvref_t<V>> &&
        plain_writable<T, V> &&
        makeable<T, V>
    ) ||
    (
        Kind == branch_kind::structural &&
        !std::same_as<T, std::remove_cvref_t<V>> &&
        (
            std::same_as<attribute_category_t<T>, container_tag> ||
            std::same_as<attribute_category_t<T>, optional_tag> ||
            std::same_as<attribute_category_t<T>, variant_tag> ||
            SameSizeTupleLike<T, V>
        )
    ) ||
    (
        Kind == branch_kind::wrapping &&
        SingleElementTupleLike<T> &&
        !std::same_as<T, std::remove_cvref_t<V>> &&
        std::is_default_constructible_v<T> &&
        is_convertible_without_narrowing_v<V, storage_t<alloy::tuple_element_t<0, T>>>
    );

// The branches of `Kind` from the candidates among `Ss`
template<branch_kind Kind, class V, class... Ss, std::size_t... Is>
consteval auto variant_branches(std::index_sequence<Is...>)
{
    using candidates = concat_type_list<std::conditional_t<
        variant_candidate<Kind, storage_t<Ss>, V>,
        type_list<std::integral_constant<std::size_t, Is>>,
        type_list<>
    >...>::type;

    return []<std::size_t... Js>(type_list<std::integral_constant<std::size_t, Js>...>) {
        if constexpr (Kind == branch_kind::same_alternative) {
            return branch_list<branch<
                Kind, Js, makeable<storage_t<pack_indexing_t<Js, Ss...>>, V>,
                edge<write_node<storage_t<pack_indexing_t<Js, Ss...>>, V>, false>
            >...>;

        } else if constexpr (Kind == branch_kind::conversion) {
            // The imaginary function F_j(S_j) of each candidate, called with the value
            using overloads = conversion_overloads<conversion_overload<Js, storage_t<pack_indexing_t<Js, Ss...>>>...>;

            if constexpr (conversion_resolves<overloads, V>) {
                // exactly one candidate is selected
                constexpr std::size_t selected = ((conversion_selects<overloads, V, Js> ? Js : 0) + ... + 0);
                return branch_list<branch<Kind, selected, true>>;

            } else {
                return branch_list<branch<Kind, no_index, sizeof...(Js) != 0>>;
            }

        } else if constexpr (Kind == branch_kind::structural) {
            return branch_list<branch_group<branch<
                Kind, Js, makeable<storage_t<pack_indexing_t<Js, Ss...>>, V>,
                edge<write_node<storage_t<pack_indexing_t<Js, Ss...>>, V>, false>
            >...>>;

        } else if constexpr (sizeof...(Js) == 1) {
            constexpr std::size_t J = cpack_indexing_v<0, Js...>;
            using wrapper = storage_t<pack_indexing_t<J, Ss...>>;

            // the child is the element, so the wrapper is checked here
            static_assert(mandates_no_const_part<wrapper>);

            using element = storage_t<alloy::tuple_element_t<0, wrapper>>;

            // A value is wrapped only when it becomes the element as it is, or by a standard conversion
            return branch_list<branch<
                Kind, J,
                std::same_as<element, std::remove_cvref_t<V>> || (std::is_scalar_v<std::remove_cvref_t<V>> && std::is_scalar_v<element>),
                edge<write_node<element, V>, false>
            >>;

        } else if constexpr (sizeof...(Js) >= 2) {
            return branch_list<branch<branch_kind::wrapping_many, no_index, true>>;

        } else {
            return branch_list<branch_group<>>;
        }
    }(candidates{});
}

template<branch_kind Kind, class V, class... Ss>
using variant_branches_t = decltype(detail::variant_branches<Kind, V, Ss...>(std::index_sequence_for<Ss...>{}))::type;

// The branches of W(S, V)
template<class S, class V>
consteval auto write_branches()
{
    using SCategory = attribute_category_t<S>;
    using VCategory = attribute_category_t<std::remove_cvref_t<V>>;

    if constexpr (std::same_as<SCategory, plain_tag>) {
        if constexpr (std::same_as<VCategory, optional_tag>) {
            return branch_list<transparent_branch<S, V>>;

        } else if constexpr (std::same_as<std::remove_cvref_t<V>, S>) {
            return branch_list<branch<branch_kind::assign_same, no_index, weakly_assignable_from<S&, V>>>;

        } else {
            return branch_list<branch<branch_kind::assign, no_index, plain_writable<S, V>>>;
        }

    } else if constexpr (std::same_as<SCategory, container_tag>) {
        // A container is appended with a range only. One integer makes a container in more than one
        // way (`std::vector<std::size_t>(3)` has 3 elements, `{3}` one, and `std::vector<std::string>{3}`
        // three), and C++ rejects every implicit form (`std::vector<std::size_t> v = std::size_t{3};`).
        if constexpr (std::same_as<VCategory, optional_tag>) {
            return branch_list<transparent_branch<S, V>>;

        } else if constexpr (range_value<V>) {
            return branch_list<
                branch<branch_kind::whole, no_index, writes_whole_as_element<S, V>, edge<write_node<storage_t<iris::container::element_t<S>>, V>, false>>,
                branch<branch_kind::append_all, no_index, appends_all<S, V>>,
                branch<branch_kind::each, no_index, true, edge<range_element_node<S, range_element_value_t<V>>, true>>
            >;

        } else {
            return branch_list<>;
        }

    } else if constexpr (std::same_as<SCategory, tuple_tag>) {
        if constexpr (SameSizeTupleLike<S, V>) {
            return []<std::size_t... Is>(std::index_sequence<Is...>) {
                return branch_list<branch<
                    branch_kind::slots, no_index, true,
                    edge<write_node<storage_t<alloy::tuple_element_t<Is, S>>, slot_value_t<Is, V>>, true>...
                >>;
            }(std::make_index_sequence<alloy::tuple_size_v<S>>{});

        } else if constexpr (alloy::tuple_size_v<S> == 1) {
            return branch_list<branch<branch_kind::single_slot, no_index, true, edge<write_node<storage_t<alloy::tuple_element_t<0, S>>, V>, false>>>;

        } else if constexpr (std::same_as<VCategory, optional_tag>) {
            return branch_list<transparent_branch<S, V>>;

        } else {
            return branch_list<>;
        }

    } else if constexpr (std::same_as<SCategory, optional_tag>) {
        using content = storage_t<typename S::value_type>;

        if constexpr (std::same_as<VCategory, optional_tag>) {
            return branch_list<branch<
                branch_kind::engage_optional, no_index, makeable<content, content_value_t<V>>,
                edge<write_node<content, content_value_t<V>>, true>
            >>;

        } else {
            return branch_list<branch<branch_kind::engage, no_index, makeable<content, V>, edge<write_node<content, V>, false>>>;
        }

    } else if constexpr (std::same_as<SCategory, variant_tag>) {
        return []<class... Ss>(std::type_identity<rvariant<Ss...>>) {
            using same = variant_branches_t<branch_kind::same_alternative, V, Ss...>;

            if constexpr (std::same_as<VCategory, optional_tag>) {
                return std::type_identity<typename concat_type_list<same, type_list<transparent_branch<S, V>>>::type>{};

            } else if constexpr (std::same_as<VCategory, variant_tag>) {
                // alternative by alternative of the value
                return []<std::size_t... Is>(std::index_sequence<Is...>) {
                    return std::type_identity<typename concat_type_list<
                        same,
                        type_list<branch<branch_kind::split, no_index, true, edge<write_node<S, part_value_t<V, decltype(iris::get<Is>(std::declval<V&>()))>>, true>...>>,
                        variant_branches_t<branch_kind::wrapping, V, Ss...>
                    >::type>{};
                }(std::make_index_sequence<variant_size_v<std::remove_cvref_t<V>>>{});

            } else {
                return std::type_identity<typename concat_type_list<
                    same,
                    variant_branches_t<branch_kind::conversion, V, Ss...>,
                    variant_branches_t<branch_kind::structural, V, Ss...>,
                    variant_branches_t<branch_kind::wrapping, V, Ss...>
                >::type>{};
            }
        }(std::type_identity<S>{});

    } else {
        return branch_list<>;
    }
}

// The new element of E(S, x) and P(S, y), made from the value
template<class S, class V>
using new_element_branch = branch<
    branch_kind::new_element, no_index,
    makeable<storage_t<iris::container::element_t<S>>, V> && iris::container::appendable<S, iris::container::element_t<S>>,
    edge<write_node<storage_t<iris::container::element_t<S>>, V>, false>
>;

// The branches of E(S, x) and P(S, y): New, then Parts for a sequence value; an optional value through
// its content; a range value of P(S, y) appended as a range
template<template<class, class> class Node, class S, class V>
consteval auto part_branches()
{
    using element = storage_t<iris::container::element_t<S>>;

    // An optional value is written through its content, unless the element takes it as it is
    if constexpr (
        std::same_as<attribute_category_t<std::remove_cvref_t<V>>, optional_tag> &&
        !std::same_as<attribute_category_t<element>, optional_tag> &&
        !has_alternative_of<element, std::remove_cvref_t<V>>
    ) {
        return branch_list<branch<branch_kind::transparent, no_index, true, edge<Node<S, content_value_t<V>>, true>>>;

    } else if constexpr (std::same_as<attribute_category_t<std::remove_cvref_t<V>>, tuple_tag>) {
        // The parts are written through P(S, y), also from E(S, x)
        return []<std::size_t... Is>(std::index_sequence<Is...>) {
            return branch_list<
                new_element_branch<S, V>,
                branch<branch_kind::parts, no_index, true, edge<sequence_part_node<S, slot_value_t<Is, V>>, true>...>
            >;
        }(std::make_index_sequence<alloy::tuple_size_v<std::remove_cvref_t<V>>>{});

    } else if constexpr (!std::same_as<Node<S, V>, range_element_node<S, V>> && range_value<V>) {
        return branch_list<branch<branch_kind::range, no_index, true, edge<write_node<S, V>, false>>>;

    } else {
        return branch_list<new_element_branch<S, V>>;
    }
}

template<class Node>
struct branches_of;

template<class S, class V>
struct branches_of<write_node<S, V>>
{
    static_assert(!std::is_reference_v<S> && !std::is_const_v<S>, "[BUG] A storage is an object type");
    static_assert(mandates_no_const_part<S>);
    static_assert(mandates_variant_default_state<S>);

    using type = decltype(detail::write_branches<S, V>())::type;
};

template<template<class, class> class Node, class S, class V>
struct branches_of<Node<S, V>>
{
    using type = decltype(detail::part_branches<Node, S, V>())::type;
};

// The graph of the nodes reachable from a root, one rule instantiation per explored node. A node is
// explored branch by branch in the order of priority, only as far as its selection needs: first up
// to the first branch which may apply, then one such branch more at a time while the explored
// graph does not make the node writable. Writability, the usable candidates and the selections are
// computed over arrays.

// A branch, or a candidate of a group
struct graph_item
{
    std::size_t position = 0;
    branch_kind kind = branch_kind::assign;
    bool cond = false;
    std::size_t alternative = no_index;
    std::size_t first_edge = 0; // in the edges of the graph
    std::size_t last_edge = 0;
};

struct graph_edge
{
    std::size_t child = 0;
    bool descent = false;
};

// The arrays of the graph, filled node by node. The children of the node being filled are given
// in the order of its edges, so that filling a node does not depend on the graph.
struct graph_output
{
    graph_item* items = nullptr;
    graph_edge* edges = nullptr;
    std::size_t item_index = 0;
    std::size_t edge_index = 0;
    std::size_t const* children = nullptr;

    constexpr void add_edge(bool const descent) noexcept
    {
        edges[edge_index] = graph_edge{*children++, descent};
        ++edge_index;
    }
};

template<class Branch>
struct branch_shape;

template<branch_kind Kind, std::size_t Alternative, bool Cond, class... Edges>
struct branch_shape<branch<Kind, Alternative, Cond, Edges...>>
{
    static constexpr bool may_apply = Cond;
    static constexpr std::size_t items = 1;
    static constexpr std::size_t edges = Cond ? sizeof...(Edges) : 0;

    static constexpr void fill(graph_output& out, std::size_t position) noexcept
    {
        out.items[out.item_index++] = graph_item{position, Kind, Cond, Alternative, out.edge_index, out.edge_index + edges};
        if constexpr (Cond) {
            (out.add_edge(Edges::descent), ...);
        }
    }
};

template<class... Branches>
struct branch_shape<branch_group<Branches...>>
{
    static constexpr bool may_apply = (branch_shape<Branches>::may_apply || ...);
    static constexpr std::size_t items = sizeof...(Branches);
    static constexpr std::size_t edges = (branch_shape<Branches>::edges + ... + 0);

    static constexpr void fill([[maybe_unused]] graph_output& out, [[maybe_unused]] std::size_t position) noexcept
    {
        (branch_shape<Branches>::fill(out, position), ...);
    }
};

template<class Branches>
struct node_shape;

template<class... Branches>
struct node_shape<type_list<Branches...>>
{
    static constexpr std::size_t branch_count = sizeof...(Branches);

    // The prefix explored after `prefix` branches: through the next branch which may apply, or all
    [[nodiscard]] static constexpr std::size_t next_prefix(std::size_t prefix) noexcept
    {
        constexpr bool may_apply[]{branch_shape<Branches>::may_apply..., false};
        for (std::size_t i = prefix; i < branch_count; ++i) {
            if (may_apply[i]) return i + 1;
        }
        return branch_count;
    }

    [[nodiscard]] static constexpr std::size_t items_before(std::size_t prefix) noexcept
    {
        constexpr std::size_t counts[]{branch_shape<Branches>::items..., 0};
        std::size_t items = 0;
        for (std::size_t i = 0; i < prefix; ++i) {
            items += counts[i];
        }
        return items;
    }

    [[nodiscard]] static constexpr std::size_t edges_before(std::size_t prefix) noexcept
    {
        constexpr std::size_t counts[]{branch_shape<Branches>::edges..., 0};
        std::size_t edges = 0;
        for (std::size_t i = 0; i < prefix; ++i) {
            edges += counts[i];
        }
        return edges;
    }

    // The items and the edges of the first `Prefix` branches
    template<std::size_t Prefix>
    static constexpr void fill(graph_output& out) noexcept
    {
        [&]<std::size_t... Is>(std::index_sequence<Is...>) {
            (branch_shape<pack_indexing_t<Is, Branches...>>::fill(out, Is), ...);
        }(std::make_index_sequence<Prefix>{});
    }
};

template<class Node>
using node_shape_t = node_shape<typename branches_of<Node>::type>;

template<class Branch>
struct branch_children
{
    using type = type_list<>;
};

template<branch_kind Kind, std::size_t Alternative, class... Edges>
struct branch_children<branch<Kind, Alternative, true, Edges...>>
{
    using type = type_list<typename Edges::node...>;
};

template<class... Branches>
struct branch_children<branch_group<Branches...>>
{
    using type = concat_type_list<typename branch_children<Branches>::type...>::type;
};

// The children of the first `Prefix` branches
template<class Node, std::size_t Prefix, class Branches = typename branches_of<Node>::type, class Is = std::make_index_sequence<Prefix>>
struct explored_children;

template<class Node, std::size_t Prefix, class... Branches, std::size_t... Is>
struct explored_children<Node, Prefix, type_list<Branches...>, std::index_sequence<Is...>>
{
    using type = concat_type_list<typename branch_children<pack_indexing_t<Is, Branches...>>::type...>::type;
};

// The children of the prefix to which a node is explored first
template<class Node>
struct initial_children : explored_children<Node, node_shape_t<Node>::next_prefix(0)> {};

template<class Node>
struct all_children : explored_children<Node, node_shape_t<Node>::branch_count> {};

// Breadth first, one frontier at a time, a node reaching `Children<Node>::type`: the frontier and the
// nodes found from it, other than `Seen`
template<template<class> class Children, class Seen, class Frontier>
struct graph_walk;

// IntelliSense (EDG) loses the type when a constrained partial specialization recurses into its
// primary template, so an empty frontier has its own partial specialization
template<template<class> class Children, class... Seen>
struct graph_walk<Children, type_list<Seen...>, type_list<>>
{
    using type = type_list<>;
};

template<template<class> class Children, class... Seen, class Node, class... Nodes>
struct graph_walk<Children, type_list<Seen...>, type_list<Node, Nodes...>>
{
    using added = unique_type_list<
        typename concat_type_list<typename Children<Node>::type, typename Children<Nodes>::type...>::type,
        type_list<Seen..., Node, Nodes...>
    >::type;

    using type = concat_type_list<
        type_list<Node, Nodes...>,
        typename graph_walk<Children, type_list<Seen..., Node, Nodes...>, added>::type
    >::type;
};

struct branch_selection
{
    std::size_t branch_index = no_index;
    std::size_t alternative_index = no_index; // of the variant written into, if any
    branch_kind kind = branch_kind::assign; // of the branch, or of the candidate selected
    bool is_ambiguous = false;
};

struct graph_view
{
    std::size_t node_count = 0;
    std::size_t const* first_item = nullptr; // of each node, then the end of the items
    graph_item const* items = nullptr;
    graph_edge const* edges = nullptr;
    std::size_t edge_count = 0;
    bool const* complete = nullptr; // each node explored to its last branch
};

struct solver_result
{
    write_rank rank = write_rank::none; // of the root
    bool needs_extension = false; // a node is to be explored further
    bool has_zero_cycle = false; // among the zero edges of the branches which apply
};

struct node_state
{
    std::size_t component = 0; // of the zero edges of the branches which apply, from 1
    std::size_t first_child = 0; // through such an edge, in `ws_.children`
    std::size_t next_child = 0;
    std::size_t order = 0; // of Tarjan's algorithm, from 1
    std::size_t low = 0;
    std::size_t chosen_item = no_index;
    std::size_t zero_parents = 0; // through the zero edges of the plan

    bool is_writable = false;
    bool ok = false; // in the fixpoint being computed
    bool is_derived = false; // in the least fixpoint being computed
    bool is_visited = false; // by the plan
};

// The arrays `graph_solver` works on, allocated by the caller as the sizes are known there.
struct graph_workspace
{
    node_state* nodes = nullptr; // and one past the last, for the end of the children of the last
    bool* applies = nullptr; // of each item
    std::size_t* children = nullptr; // of each edge
    std::size_t* stack = nullptr; // of each node
    std::size_t* calls = nullptr;
    std::size_t* pending = nullptr;
};

// The selections of the nodes of a graph and the rank of its root, the first node. Not a template:
// every graph is solved by the same function, over arrays.
class graph_solver
{
public:
    constexpr graph_solver(graph_view const& graph, graph_workspace const& ws) noexcept
        : graph_(graph)
        , ws_(ws)
    {}

    graph_solver(graph_solver const&) = delete;
    graph_solver& operator=(graph_solver const&) = delete;

    // The selections, the nodes to explore further, and the rank of the root
    [[nodiscard]] constexpr solver_result solve(branch_selection* selections, bool* extend) noexcept
    {
        std::size_t const node_count = graph_.node_count;
        solver_result result;

        find_writable(no_index, no_index);
        for (std::size_t node = 0; node < node_count; ++node) {
            ws_.nodes[node].is_writable = ws_.nodes[node].ok;
        }

        // a node not writable by the branches explored so far may be by the others
        for (std::size_t node = 0; node < node_count; ++node) {
            if (!ws_.nodes[node].is_writable && !graph_.complete[node]) {
                extend[node] = true;
                result.needs_extension = true;
            }
        }
        if (result.needs_extension) return result;

        // a branch applies if its condition holds and its children are writable
        for (std::size_t node = 0; node < node_count; ++node) {
            for (std::size_t i = graph_.first_item[node]; i != graph_.first_item[node + 1]; ++i) {
                ws_.applies[i] = ws_.nodes[node].is_writable && applies(graph_.items[i]);
            }
        }
        find_components();
        for (std::size_t node = 0; node < node_count; ++node) {
            for (std::size_t i = graph_.first_item[node]; i != graph_.first_item[node + 1]; ++i) {
                result.has_zero_cycle = result.has_zero_cycle || (ws_.applies[i] && cyclic(node, graph_.items[i]));
            }
        }

        // the selection: the first position with a usable candidate
        for (std::size_t node = 0; node < node_count; ++node) {
            if (!ws_.nodes[node].is_writable) continue;

            branch_selection& selection = selections[node];
            std::size_t candidates = 0;
            for (std::size_t i = graph_.first_item[node]; i != graph_.first_item[node + 1]; ++i) {
                graph_item const& item = graph_.items[i];
                if (selection.branch_index != no_index && item.position != selection.branch_index) break;
                if (!usable(node, i)) continue;

                selection.branch_index = item.position;
                selection.kind = item.kind;
                selection.alternative_index = item.alternative;
                selection.is_ambiguous = item.kind == branch_kind::wrapping_many || (item.kind == branch_kind::conversion && item.alternative == no_index);
                ws_.nodes[node].chosen_item = i;
                ++candidates;
            }
            if (candidates >= 2) {
                selection.alternative_index = no_index;
                selection.is_ambiguous = true;
            }
        }

        if (ws_.nodes[0].is_writable) {
            result.rank = plan_rank(selections);
        }
        return result;
    }

private:
    // The rank of the plan: the nodes reached through the selections, none of them ambiguous, and
    // no cycle of the zero edges among them (a conflict of the selections)
    [[nodiscard]] constexpr write_rank plan_rank(branch_selection const* selected) noexcept
    {
        bool converts = false;
        std::size_t plan_size = 0; // in `ws_.stack`
        std::size_t pending = 0;
        ws_.pending[pending++] = 0;
        ws_.nodes[0].is_visited = true;
        while (pending != 0) {
            std::size_t const node = ws_.pending[--pending];
            if (selected[node].is_ambiguous) return write_rank::none;

            ws_.stack[plan_size++] = node;
            graph_item const& item = graph_.items[ws_.nodes[node].chosen_item];
            converts = converts || item.kind == branch_kind::assign || item.kind == branch_kind::conversion;
            for (std::size_t e = item.first_edge; e != item.last_edge; ++e) {
                graph_edge const& edge = graph_.edges[e];
                if (!edge.descent) {
                    ++ws_.nodes[edge.child].zero_parents;
                }
                if (ws_.nodes[edge.child].is_visited) continue;

                ws_.nodes[edge.child].is_visited = true;
                ws_.pending[pending++] = edge.child;
            }
        }

        // the zero edges of the plan without a cycle: every node is removed, one without a zero parent at a time
        std::size_t removed = 0;
        for (std::size_t k = 0; k != plan_size; ++k) {
            if (ws_.nodes[ws_.stack[k]].zero_parents == 0) {
                ws_.pending[pending++] = ws_.stack[k];
            }
        }
        while (pending != 0) {
            graph_item const& item = graph_.items[ws_.nodes[ws_.pending[--pending]].chosen_item];
            ++removed;
            for (std::size_t e = item.first_edge; e != item.last_edge; ++e) {
                graph_edge const& edge = graph_.edges[e];
                if (!edge.descent && --ws_.nodes[edge.child].zero_parents == 0) {
                    ws_.pending[pending++] = edge.child;
                }
            }
        }
        if (removed != plan_size) return write_rank::none;

        return
            graph_.items[ws_.nodes[0].chosen_item].kind == branch_kind::assign_same ? write_rank::exact :
            converts ? write_rank::assignable_without_narrowing :
            write_rank::structural;
    }

    // Writable: the greatest fixpoint over the descent edges of the least one over the zero edges; a cycle
    // is written through only where the value descends (a tree flattened), never while it stays the same.
    // With `restricted_node`, that node takes `restricted_item` only.
    constexpr void find_writable(std::size_t restricted_node, std::size_t restricted_item) noexcept
    {
        std::size_t const node_count = graph_.node_count;
        restricted_node_ = restricted_node;
        restricted_item_ = restricted_item;

        // a node none of whose branches has its condition is never writable
        for (std::size_t node = 0; node < node_count; ++node) {
            ws_.nodes[node].ok = false;
            for (std::size_t i = first_item(node); i != last_item(node); ++i) {
                if (graph_.items[i].cond) {
                    ws_.nodes[node].ok = true;
                    break;
                }
            }
        }
        while (true) {
            // the least fixpoint in place over the nodes not derived yet, the last node first as a child
            // mostly follows its parent
            std::size_t pending = 0;
            for (std::size_t node = node_count; node-- != 0;) {
                ws_.nodes[node].is_derived = false;
                if (ws_.nodes[node].ok) {
                    ws_.pending[pending++] = node;
                }
            }
            for (std::size_t before = pending + 1; pending != before;) { // until a pass derives none
                before = pending;
                pending = 0;
                for (std::size_t k = 0; k != before; ++k) {
                    std::size_t const node = ws_.pending[k];
                    if (derivable_node(node)) {
                        ws_.nodes[node].is_derived = true;
                    } else {
                        ws_.pending[pending++] = node;
                    }
                }
            }
            if (pending == 0) break;

            for (std::size_t k = 0; k != pending; ++k) {
                ws_.nodes[ws_.pending[k]].ok = false;
            }
        }
    }

    [[nodiscard]] constexpr std::size_t first_item(std::size_t node) const noexcept
    {
        return node == restricted_node_ ? restricted_item_ : graph_.first_item[node];
    }

    [[nodiscard]] constexpr std::size_t last_item(std::size_t node) const noexcept
    {
        return node == restricted_node_ ? restricted_item_ + 1 : graph_.first_item[node + 1];
    }

    [[nodiscard]] constexpr bool derivable_node(std::size_t node) const noexcept
    {
        for (std::size_t i = first_item(node); i != last_item(node); ++i) {
            if (derivable(graph_.items[i])) return true;
        }
        return false;
    }

    // A child through a descent edge is in the fixpoint, and one through a zero edge derived
    [[nodiscard]] constexpr bool derivable(graph_item const& item) const noexcept
    {
        if (!item.cond) return false;

        for (std::size_t e = item.first_edge; e != item.last_edge; ++e) {
            graph_edge const& edge = graph_.edges[e];
            if (edge.descent ? !ws_.nodes[edge.child].ok : !ws_.nodes[edge.child].is_derived) return false;
        }
        return true;
    }

    [[nodiscard]] constexpr bool applies(graph_item const& item) const noexcept
    {
        if (!item.cond) return false;

        for (std::size_t e = item.first_edge; e != item.last_edge; ++e) {
            if (!ws_.nodes[graph_.edges[e].child].is_writable) return false;
        }
        return true;
    }

    // A zero edge of the item returns to the node through the zero edges of the branches which apply
    [[nodiscard]] constexpr bool cyclic(std::size_t node, graph_item const& item) const noexcept
    {
        for (std::size_t e = item.first_edge; e != item.last_edge; ++e) {
            graph_edge const& edge = graph_.edges[e];
            if (!edge.descent && ws_.nodes[edge.child].component == ws_.nodes[node].component) return true;
        }
        return false;
    }

    // A finite write takes the item at the node, the other nodes taking any of theirs
    [[nodiscard]] constexpr bool usable(std::size_t node, std::size_t i) noexcept
    {
        if (!ws_.applies[i]) return false;
        if (!cyclic(node, graph_.items[i])) return true;

        find_writable(node, i);
        return ws_.nodes[node].ok;
    }

    // The strongly connected components of the zero edges of the branches which apply, by Tarjan's
    // algorithm without recursion
    constexpr void find_components() noexcept
    {
        std::size_t const node_count = graph_.node_count;

        std::size_t child_count = 0;
        for (std::size_t node = 0; node < node_count; ++node) {
            node_state& state = ws_.nodes[node];
            state.first_child = state.next_child = child_count;
            for (std::size_t i = graph_.first_item[node]; i != graph_.first_item[node + 1]; ++i) {
                if (!ws_.applies[i]) continue;

                for (std::size_t e = graph_.items[i].first_edge; e != graph_.items[i].last_edge; ++e) {
                    if (!graph_.edges[e].descent) {
                        ws_.children[child_count++] = graph_.edges[e].child;
                    }
                }
            }
        }
        ws_.nodes[node_count].first_child = child_count;

        std::size_t stack_size = 0;
        std::size_t call_count = 0;
        std::size_t next_order = 1;
        std::size_t next_component = 1;
        for (std::size_t root = 0; root < node_count; ++root) {
            if (ws_.nodes[root].order != 0) continue;

            ws_.nodes[root].order = ws_.nodes[root].low = next_order++;
            ws_.stack[stack_size++] = root;
            ws_.calls[call_count++] = root;

            while (call_count != 0) {
                std::size_t const node = ws_.calls[call_count - 1];
                node_state& state = ws_.nodes[node];
                if (state.next_child != ws_.nodes[node + 1].first_child) {
                    std::size_t const child = ws_.children[state.next_child++];
                    node_state& child_state = ws_.nodes[child];
                    if (child_state.order == 0) {
                        child_state.order = child_state.low = next_order++;
                        ws_.stack[stack_size++] = child;
                        ws_.calls[call_count++] = child;

                    } else if (child_state.component == 0 && child_state.order < state.low) { // on the stack
                        state.low = child_state.order;
                    }
                    continue;
                }

                if (state.low == state.order) {
                    std::size_t member = no_index;
                    do {
                        member = ws_.stack[--stack_size];
                        ws_.nodes[member].component = next_component;
                    } while (member != node);
                    ++next_component;
                }
                --call_count;
                if (call_count != 0 && state.low < ws_.nodes[ws_.calls[call_count - 1]].low) {
                    ws_.nodes[ws_.calls[call_count - 1]].low = state.low;
                }
            }
        }
    }

    graph_view graph_;
    graph_workspace ws_;
    std::size_t restricted_node_ = no_index;
    std::size_t restricted_item_ = no_index;
};

template<std::size_t NodeCount>
struct graph_solution
{
    std::array<branch_selection, NodeCount> selections{};
    std::array<bool, NodeCount> needs_extension{};
    solver_result result;
};

// The indices in the graph `Nodes` of the children of a node, in the order of its edges (and one
// more element: MSVC rejects an array of no element in a constant evaluation)
template<class Nodes, class Children>
inline constexpr std::array<std::size_t, 1> child_indices{};

template<class Nodes, class... Children>
inline constexpr std::array<std::size_t, sizeof...(Children) + 1> child_indices<Nodes, type_list<Children...>>{find_index_exactly_once_v<Children, Nodes>..., 0};

template<class... Nodes, std::size_t... Prefixes, std::size_t... Is>
[[nodiscard]] constexpr graph_solution<sizeof...(Nodes)> solve_nodes(type_list<Nodes...>, constant_list<Prefixes...>, std::index_sequence<Is...>)
{
    constexpr std::size_t item_count = (node_shape_t<Nodes>::items_before(Prefixes) + ... + 0);
    constexpr std::size_t edge_count = (node_shape_t<Nodes>::edges_before(Prefixes) + ... + 0);

    std::array<std::size_t, sizeof...(Nodes) + 1> first_item{};
    std::array<graph_item, item_count> items{};
    std::array<graph_edge, edge_count> edges{};
    std::array<bool, sizeof...(Nodes)> const complete{(Prefixes == node_shape_t<Nodes>::branch_count)...};

    graph_output out{items.data(), edges.data()};
    (
        (
            first_item[Is] = out.item_index,
            out.children = child_indices<type_list<Nodes...>, typename explored_children<Nodes, Prefixes>::type>.data(),
            node_shape_t<Nodes>::template fill<Prefixes>(out)
        ),
        ...
    );
    first_item[sizeof...(Nodes)] = out.item_index;

    std::array<node_state, sizeof...(Nodes) + 1> nodes{};
    std::array<bool, item_count> applies{};
    std::array<std::size_t, edge_count> children{};
    std::array<std::size_t, sizeof...(Nodes)> stack{};
    std::array<std::size_t, sizeof...(Nodes)> calls{};
    std::array<std::size_t, sizeof...(Nodes)> pending{};

    graph_solution<sizeof...(Nodes)> solution;
    solution.result = graph_solver(
        graph_view{
            .node_count = sizeof...(Nodes),
            .first_item = first_item.data(),
            .items = items.data(),
            .edges = edges.data(),
            .edge_count = edges.size(),
            .complete = complete.data(),
        },
        graph_workspace{
            .nodes = nodes.data(),
            .applies = applies.data(),
            .children = children.data(),
            .stack = stack.data(),
            .calls = calls.data(),
            .pending = pending.data(),
        }
    ).solve(solution.selections.data(), solution.needs_extension.data());
    return solution;
}

// The graph of `Nodes`, each explored to its prefix in `Prefixes`
template<class Nodes, class Prefixes, class Is = std::make_index_sequence<Nodes::size>>
struct explored_graph;

template<class... Nodes, std::size_t... Prefixes, std::size_t... Is>
struct explored_graph<type_list<Nodes...>, constant_list<Prefixes...>, std::index_sequence<Is...>>
{
    using nodes = type_list<Nodes...>;

    static constexpr graph_solution<sizeof...(Nodes)> solution = detail::solve_nodes(nodes{}, constant_list<Prefixes...>{}, std::index_sequence<Is...>{});

    static constexpr bool is_complete = ((Prefixes == node_shape_t<Nodes>::branch_count) && ...);

    using next_prefixes = constant_list<(solution.needs_extension[Is] ? node_shape_t<Nodes>::next_prefix(Prefixes) : Prefixes)...>;

    template<class Node>
    static constexpr branch_selection selection_of = solution.selections[find_index_exactly_once_v<Node, nodes>];
};

// ReSharper fails to compute the graph in a constraint when a function deduces it as its return
// type, so the graph is computed by class templates only
template<class Known, class Prefixes>
struct explore;

template<class Nodes>
struct explore_completely;

template<class... Nodes>
struct explore_completely<type_list<Nodes...>>
{
    using type = explored_graph<type_list<Nodes...>, constant_list<node_shape_t<Nodes>::branch_count...>>;
};

// The graph after the round that explored `Graph`
template<class Graph, bool Extend = Graph::solution.result.needs_extension, bool Partial = Graph::solution.result.has_zero_cycle && !Graph::is_complete>
struct next_round
{
    using type = Graph;
};

template<class Graph, bool Partial>
struct next_round<Graph, true, Partial> : explore<typename Graph::nodes, typename Graph::next_prefixes> {};

// from the nodes of the graph, the root first
template<class Graph>
struct next_round<Graph, false, true> : explore_completely<typename graph_walk<all_children, type_list<>, typename Graph::nodes>::type> {};

template<class Known, class Prefixes, class Reached>
struct explore_round;

template<class... Known, std::size_t... Prefixes, class... Reached>
struct explore_round<type_list<Known...>, constant_list<Prefixes...>, type_list<Reached...>>
    : next_round<explored_graph<type_list<Known..., Reached...>, constant_list<Prefixes..., node_shape_t<Reached>::next_prefix(0)...>>>
{};

// The graph explored round by round: the nodes `Known`, explored to `Prefixes`, stay first in
// their order, and the nodes reached from them are explored to their first prefixes. A graph is explored
// further while a node is not writable by the branches explored so far. The usable candidates on a cycle
// of zero edges may depend on the branches not explored, so such a graph is then explored completely.
template<class... Known, std::size_t... Prefixes>
struct explore<type_list<Known...>, constant_list<Prefixes...>>
    : explore_round<
        type_list<Known...>,
        constant_list<Prefixes...>,
        typename graph_walk<
            initial_children,
            type_list<Known...>,
            typename unique_type_list<typename concat_type_list<typename explored_children<Known, Prefixes>::type...>::type, type_list<Known...>>::type
        >::type
    >
{};

} // detail

// The write the selection of a node performs, which the parse side follows (the part a parser
// writes into, and whether a container takes a value as a new element or appended by the parser)
struct node_write_strategy
{
    constexpr node_write_strategy(write_rank rank, detail::branch_selection const& selection) noexcept
        : is_writable(rank != write_rank::none)
        , kind(selection.kind)
        , alternative_index(selection.alternative_index)
    {}

    bool is_writable; // the write from the node is accepted, not `write_rank::none`
    branch_kind kind; // of the branch selected, or of the candidate selected
    std::size_t alternative_index; // of the variant written into, if any
};

// The graph of the nodes reachable from `Root`, the first of them, explored as far as the selections need
template<class Root>
using graph_of = detail::explore<type_list<Root>, constant_list<detail::node_shape_t<Root>::next_prefix(0)>>::type;

template<class Node>
inline constexpr node_write_strategy node_write_strategy_of{
    graph_of<Node>::solution.result.rank,
    graph_of<Node>::template selection_of<Node>
};

} // planner

namespace detail {

template<class SRef, class V>
    requires X4UnusedAttribute<std::remove_reference_t<SRef>> || X4UnusedAttribute<std::remove_reference_t<V>>
struct write_rank_impl<SRef, V>
{
    static_assert(mandates_writable_ref<SRef>);

    static constexpr write_rank value = write_rank::none;
};

template<class SRef, class V>
    requires (!X4UnusedAttribute<std::remove_reference_t<SRef>> && !X4UnusedAttribute<std::remove_reference_t<V>>)
struct write_rank_impl<SRef, V>
{
    static_assert(mandates_writable_ref<SRef>);

    static constexpr write_rank value = planner::graph_of<
        planner::write_node<planner::storage_t<SRef>, planner::model_value_t<V>>
    >::solution.result.rank;
};

} // detail

} // iris::x4

#endif
