#ifndef IRIS_ZZ_X4_TRAITS_ATTRIBUTE_OF_BINARY_HPP
#define IRIS_ZZ_X4_TRAITS_ATTRIBUTE_OF_BINARY_HPP

/*=============================================================================
    Copyright (c) 2001-2014 Joel de Guzman
    Copyright (c) 2013 Agustin Berge
    Copyright (c) 2020 Nikita Kniazev
    Copyright (c) 2025 Nana Sakisaka
    Copyright (c) 2026 The Iris Project Contributors

    Distributed under the Boost Software License, Version 1.0. (See accompanying
    file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
=============================================================================*/

#include <iris/x4/core/unused.hpp>
#include <iris/x4/core/parser_traits.hpp>

#include <iris/type_traits.hpp>  // TODO: move iris::type_list to separate header

namespace iris::x4::traits {

namespace detail {

template<class TTypeList, class UTypeList>
struct concat_type_list;

template<class... Ts, class... Us>
struct concat_type_list<type_list<Ts...>, type_list<Us...>>
{
    using type = type_list<Ts..., Us...>;
};

#if 0
#define IRIS_X4_TRAITS_DETAIL_DEFINE_TYPE_LIST_CONV(postfix, tmpl) \
    template<class T> \
    struct to_type_list_##postfix \
    { \
        using type = type_list<T>; \
    }; \
    template<> \
    struct to_type_list_##postfix<unused_type> \
    { \
        using type = type_list<>; \
    }; \
    template<class... Ts> \
    struct to_type_list_##postfix<tmpl<Ts...>> \
    { \
        using type = type_list<Ts...>; \
    }; \
    \
    template<class TypeList> \
    struct from_type_list_##postfix {}; \
    template<> \
    struct from_type_list_##postfix<type_list<>> \
    { \
        using type = unused_type; \
    }; \
    template<class T> \
    struct from_type_list_##postfix<type_list<T>> \
    { \
        using type = T; \
    }; \
    template<class T0, class T1, class... Ts> \
    struct from_type_list_##postfix<type_list<T0, T1, Ts...>> \
    { \
        using type = tmpl<T0, T1, Ts...>; \
    }; \
    \
    template<class LeftParser, class RightParser> \
    struct attribute_of_##postfix { \
        using type = detail::from_type_list_##postfix< \
            typename detail::concat_type_list< \
                typename detail::to_type_list_##postfix<typename parser_traits<LeftParser>::attribute_type>::type, \
                typename detail::to_type_list_##postfix<typename parser_traits<RightParser>::attribute_type>::type \
            >::type \
        >::type; \
    };
#endif

//
// AUTOGENERATED CODE; DO NOT EDIT.
// Expanded using Visual Studio's "Expand Inline" feature.
// Code style is kept as-is.
//

// IRIS_X4_TRAITS_DETAIL_DEFINE_TYPE_LIST_CONV(sequence, alloy::tuple)
template<class T> struct to_type_list_sequence {
    using type = type_list<T>;
}; template<> struct to_type_list_sequence<unused_type> {
    using type = type_list<>;
}; template<class... Ts> struct to_type_list_sequence<alloy::tuple<Ts...>> {
    using type = type_list<Ts...>;
}; template<class TypeList> struct from_type_list_sequence {}; template<> struct from_type_list_sequence<type_list<>> {
    using type = unused_type;
}; template<class T> struct from_type_list_sequence<type_list<T>> {
    using type = T;
}; template<class T0, class T1, class... Ts> struct from_type_list_sequence<type_list<T0, T1, Ts...>> {
    using type = alloy::tuple<T0, T1, Ts...>;
}; template<class LeftParser, class RightParser> struct attribute_of_sequence {
    using type = detail::from_type_list_sequence< typename detail::concat_type_list< typename detail::to_type_list_sequence<typename parser_traits<LeftParser>::attribute_type>::type, typename detail::to_type_list_sequence<typename parser_traits<RightParser>::attribute_type>::type >::type >::type;
};

// IRIS_X4_TRAITS_DETAIL_DEFINE_TYPE_LIST_CONV(alternative, rvariant)
template<class T> struct to_type_list_alternative {
    using type = type_list<T>;
}; template<> struct to_type_list_alternative<unused_type> {
    using type = type_list<>;
}; template<class... Ts> struct to_type_list_alternative<rvariant<Ts...>> {
    using type = type_list<Ts...>;
}; template<class TypeList> struct from_type_list_alternative {}; template<> struct from_type_list_alternative<type_list<>> {
    using type = unused_type;
}; template<class T> struct from_type_list_alternative<type_list<T>> {
    using type = T;
}; template<class T0, class T1, class... Ts> struct from_type_list_alternative<type_list<T0, T1, Ts...>> {
    using type = rvariant<T0, T1, Ts...>;
}; template<class LeftParser, class RightParser> struct attribute_of_alternative {
    using type = detail::from_type_list_alternative< typename detail::concat_type_list< typename detail::to_type_list_alternative<typename parser_traits<LeftParser>::attribute_type>::type, typename detail::to_type_list_alternative<typename parser_traits<RightParser>::attribute_type>::type >::type >::type;
};

} // detail

} // iris::x4::traits

#endif
